title: Eugene Hom
tagline: The Blog
description: Software Developer
canonical_url: https://hamstergene.github.io

author:
  name: Eugene Hom

github_username: hamstergene
repository: hamstergene/hamstergene.github.io

disqus_username: hamstergene

markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

paginate: 10

permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      comments: true

sass:
  sass_dir: /public/css

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

livereload: true
